server.port=8080
spring.datasource.url=mysql://root:zlOQnYkzrxsLtfpTlrchFRQXGwlRlXId@gondola.proxy.rlwy.net:28377/railway
spring.datasource.username=root
spring.datasource.password=zlOQnYkzrxsLtfpTlrchFRQXGwlRlXId
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
jwt.secret=streetfoodfinderSecretKey2024VeryLongSecretKeyForJWTSigning123456789
jwt.expiration=86400000
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
